from __future__ import annotations

MOUSE_LEVEL_COLUMNS = [
    "osd_id",
    "mission",
    "mouse_id",
    "source_name",
    "strain",
    "animal_source",
    "genotype",
    "sex",
    "age",
    "spaceflight_status",
    "duration",
    "habitat",
    "study_purpose",
    "n_samples_linked",
    "is_pooled_subject",
    "provenance_source",
    "confidence",
]

SAMPLE_LEVEL_COLUMNS = [
    "osd_id",
    "mission",
    "sample_id",
    "mouse_id",
    "source_name",
    "sample_name",
    "organism",
    "material_type",
    "measurement_types",
    "technology_types",
    "device_platforms",
    "assay_category",
    "assay_subtype",
    "assay_name",
    "raw_data_file",
    "is_rnaseq",
    "is_dna_methylation",
    "is_mass_spec",
    "is_rna_methylation",
    "is_metabolomics",
    "is_behavior",
    "is_atpase_activity",
    "is_calcium_uptake",
    "is_atacseq",
    "is_echocardiogram",
    "is_imaging",
    "is_western_blot",
    "assay_assignment_level",
    "provenance_source",
    "confidence",
]

ASSAY_PARAMETER_COLUMNS = [
    "osd_id",
    "mission",
    "sample_id",
    "mouse_id",
    "assay_category",
    "assay_subtype",
    "parameter_name",
    "parameter_value",
    "term_source_ref",
    "term_accession_number",
    "protocol_ref",
    "assay_name",
    "raw_data_file",
]
